/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package calculator;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test void appHasSum() {
        App classUnderTest = new App();
        int a = 10;
        int b = 20;
        assertEquals(a + b, classUnderTest.getSum(a, b), "Salah");
    }
    @Test void appHasSubstract() {
        App classUnderTest = new App();
        assertEquals(30 - 10, classUnderTest.getSubstract(30,10), "Salah");
    }
    @Test void appHasProduct() {
        App classUnderTest = new App();
        assertEquals(25 * 4, classUnderTest.getProduct(25, 4), "Salah");
    }
}
