/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package calculator;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test void appHasSum() {
        App classUnderTest = new App();
        int a = 10;
        int b = 20;
        assertEquals(a + b, classUnderTest.getSum(a, b), "Salah");

    }
}
